name: 'Continuous Delivery'

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2