name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'  
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Authenticate to Google
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/988775701050/locations/global/workloadIdentityPools/app-engine/providers/github
          service_account: app-engine@retropixel-396819.iam.gserviceaccount.com

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1