name: 'Continuous Integration'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-test.txt

      - name: Unit tests
        run: |
          make model-test
          make api-test